export const projects = [
    {
        id: "cyber-games-symfony",
        title: "Cyber Games Arras",
        description: "Plateforme web événementielle développée avec Symfony.",
        fullDescription: "Site web complet pour la gestion et la présentation de l'événement Cyber Games d'Arras. Gestion des inscriptions, des tournois et des résultats en temps réel.",
        tech: ["PHP", "Symfony", "MySQL", "Twig"],
        githubUrl: "https://github.com/KIIBA-EXE/cyber_games_arras-symfony",
        image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "cybergames-java",
        title: "CyberGames App",
        description: "Application de gestion de tournois en Java.",
        fullDescription: "Application desktop robuste pour l'organisation de tournois LAN. Gestion des équipes, des brackets et des scores avec une interface utilisateur intuitive.",
        tech: ["Java", "JavaFX", "Desktop"],
        githubUrl: "https://github.com/KIIBA-EXE/CyberGames",
        image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "scrap-stat",
        title: "Social Network Scraper",
        description: "Outil d'analyse de données et de scraping en Python.",
        fullDescription: "Script Python performant pour extraire et analyser des statistiques provenant de divers réseaux sociaux. Visualisation des données et export de rapports.",
        tech: ["Python", "Pandas", "Selenium", "Data Analysis"],
        githubUrl: "https://github.com/KIIBA-EXE/Scrap-Stat-Social-Network",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "stat-site-web",
        title: "Stat Site Web",
        description: "Site d'analyse statistique en Python.",
        fullDescription: "Projet web permettant de visualiser et d'analyser des données statistiques. Utilise Python pour le traitement backend des données.",
        tech: ["Python", "Web", "Data Visualization"],
        githubUrl: "https://github.com/KIIBA-EXE/Stat-Site-web",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "mystery",
        title: "Mystery Project",
        description: "Projet expérimental en JavaScript.",
        fullDescription: "Une application web interactive explorant des concepts avancés de JavaScript et de manipulation du DOM.",
        tech: ["JavaScript", "Web", "Experimental"],
        githubUrl: "https://github.com/KIIBA-EXE/mystery",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "blog2",
        title: "Personal Blog V2",
        description: "Moteur de blog personnel en PHP.",
        fullDescription: "Un système de blog personnalisé avec gestion des articles, commentaires et authentification utilisateur, écrit en PHP natif.",
        tech: ["PHP", "MySQL", "Blog"],
        githubUrl: "https://github.com/KIIBA-EXE/blog2",
        image: "https://images.unsplash.com/photo-1499750310159-5254f4cc65fc?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "arbrisson",
        title: "Arbrisson",
        description: "Site vitrine pour une association ou entité locale.",
        fullDescription: "Développement d'un site web statique en HTML/CSS pour présenter les activités et informations de l'entité Arbrisson.",
        tech: ["HTML", "CSS", "Static Site"],
        githubUrl: "https://github.com/KIIBA-EXE/Arbrisson",
        image: "https://images.unsplash.com/photo-1419640303358-44f0d27f48e6?auto=format&fit=crop&q=80&w=1000",
    },
    {
        id: "mathieu-portfolio",
        title: "Legacy Portfolio",
        description: "Ma première page personnelle en HTML/CSS pur.",
        fullDescription: "Version initiale de mon portfolio, démontrant mes bases solides en développement web frontend sans framework.",
        tech: ["HTML5", "CSS3", "JavaScript"],
        githubUrl: "https://github.com/KIIBA-EXE/mathieu-portfolio",
        image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=1000",
    },
];
